title: "Ola Ishola"
email: olaishola@hotmail.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/" 
form_url: "https://formspree.io/f/mnqlbokq"

twitter_username: https://twitter.com/Orlaish
t-class: fab fa-twitter-square fa-2x

github_username: https://github.com/netman5
g-class: fab fa-github fa-2x

linkedin_username: https://www.linkedin.com/olaishola 
l-class: fab fa-linkedin fa-2x

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
